IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'CA_LOGClearMechanics'
    AND COLUMN_NAME = 'mensaje'
)
BEGIN
    ALTER TABLE CA_LOGClearMechanics
    ADD mensaje VARCHAR(255) NULL;
END;
GO
IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'CA_LOGClearMechanics'
    AND COLUMN_NAME = 'orderId'
)
BEGIN
    ALTER TABLE CA_LOGClearMechanics
    ADD orderId VARCHAR(30) NULL;
END;
GO